version: "3"
services:
  api:
    build: . 
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro #syncing our local machine with the container
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=postgres  # Use the service name `postgres` as the hostname
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=9042b59af6adc2554c8167b7956393d79f9f60fe4cacefd30f8e0d367
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - postgres  # Ensure that `api` starts after `postgres`

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi
    volumes: 
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
